"""empty message

Revision ID: e3db4cb37dea
Revises: 
Create Date: 2021-08-02 18:48:54.840547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db4cb37dea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('Customer_ID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=64), nullable=True),
    sa.Column('LastName', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.Column('Phone', sa.String(length=64), nullable=True),
    sa.Column('Zip', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Customer_ID')
    )
    op.create_index(op.f('ix_Customers_Email'), 'Customers', ['Email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Customers_Email'), table_name='Customers')
    op.drop_table('Customers')
    # ### end Alembic commands ###
